{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dd-log-analyzer.fullname" . }}
  labels:
    {{- include "dd-log-analyzer.labels" . | nindent 4 }}
type: Opaque
stringData:
  DD_API_KEY: {{ .Values.secrets.datadogApiKey | quote }}
  DD_APP_KEY: {{ .Values.secrets.datadogAppKey | quote }}
  DD_SITE: {{ .Values.secrets.datadogSite | quote }}
  WEB_USERNAME: {{ .Values.secrets.webUsername | quote }}
  WEB_PASSWORD: {{ .Values.secrets.webPassword | quote }}
  WEB_SECRET_KEY: {{ .Values.secrets.webSecretKey | quote }}
  SLACK_WEBHOOK_URL: {{ .Values.secrets.slackWebhookUrl | quote }}
  JIRA_BASE_URL: {{ .Values.secrets.jiraBaseUrl | quote }}
  JIRA_EMAIL: {{ .Values.secrets.jiraEmail | quote }}
  JIRA_API_TOKEN: {{ .Values.secrets.jiraApiToken | quote }}
{{- end }}
